/*
 * generated by Xtext
 */
package eu.quanticol.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import eu.quanticol.ui.internal.CASPAActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CASPAExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CASPAActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CASPAActivator.getInstance().getInjector(CASPAActivator.EU_QUANTICOL_CASPA);
	}
	
}
