/*
 * generated by Xtext
 */
package eu.quanticol.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CASPAUiModule extends eu.quanticol.ui.AbstractCASPAUiModule {
	public CASPAUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
