/**
 * generated by Xtext
 */
package eu.quanticol.ui.contentassist;

import eu.quanticol.ui.contentassist.AbstractCASPAProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CASPAProposalProvider extends AbstractCASPAProposalProvider {
}
