/*
 * generated by Xtext
 */
package eu.quanticol;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CASPARuntimeModule extends eu.quanticol.AbstractCASPARuntimeModule {

}
