/*
* generated by Xtext
*/
package eu.quanticol.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.quanticol.services.CASPAGrammarAccess;

public class CASPAParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CASPAGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.quanticol.parser.antlr.internal.InternalCASPAParser createParser(XtextTokenStream stream) {
		return new eu.quanticol.parser.antlr.internal.InternalCASPAParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public CASPAGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CASPAGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
