/**
 * generated by Xtext
 */
package eu.quanticol.validation;

import eu.quanticol.validation.AbstractCASPAValidator;
import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CASPAValidator extends AbstractCASPAValidator {
  @Check
  public void checkType(final /* Store */Object store) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field evalExpression is undefined for the type CASPAValidator"
      + "\nCASPAPackage$Literals cannot be resolved to a type."
      + "\nThe method or field WRONG_TYPE is undefined for the type CASPAValidator"
      + "\ntypeForA cannot be resolved"
      + "\n== cannot be resolved"
      + "\nFREE_EVALUATION_EXPRESSION__EXPRESSION cannot be resolved");
  }
}
