/*
* generated by Xtext
*/
package eu.quanticol;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CASPAUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return eu.quanticol.ui.internal.CASPAActivator.getInstance().getInjector("eu.quanticol.CASPA");
	}
	
}
